### PR TITLE
feat/docs-v2.0

### PR DESCRIPTION
**Pull request by lewisdaly**
This PR brings in docs 2.0 into `master`.

Files that were changed during the long merge were automatically moved to their correct places by git it seems.

## Configure Redirects

In order to support the gradual migration to docs 2.0, we need to be able to configure the CDN 
to fall back to legacy docs that haven't yet been migrated, also be able to redirect legacy
links to updated pages in order to avoid broken links once we switch over to docs 2.0.

For this, we use cloudfront functions, which are lightweight Javascript functions that allow you 
to control the behaviour of requests and responses of the CDN.

The redirect behaviour can be configured in `./infra/src/redirect/index.js`

### CODE REVIEW

**Comment by lewisdaly** [comment]
Note: vuepress build is currently failing, and we're going to fix it in a subsequent PR.

The purpose of this PR is just to get everything merged in in preparation for the v2 launch.

**Review by elnyry-sam-k — APPROVED** [review]
can we have something like a workshop session once this is merged to review and address any issues.. but approving for now to help move this forward

**Review by mdebarros — APPROVED** [review]
+1

**Comment by lewisdaly** [comment]
> can we have something like a workshop session once this is merged to review and address any issues.. but approving for now to help move this forward

Certainly, please leave any other thoughts or comments on this issue: https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2440

**Comment by lewisdaly** [comment]
@elnyry-sam-k  - I've added a `Cleanup` section to that checklist, so if there's anything you think off, please add it there as well

**Comment by elnyry-sam-k** [comment]
Thanks @lewisdaly; added a couple to the story itself..

**Comment by lewisdaly** [comment]
Thanks :)

**Pull request merged**
