### PR TITLE
feat(puml): add svg render git commit hooks

### PR DESCRIPTION
**Pull request by lewisdaly**
This is a part of a general overhaul of our documentation.

__The purpose of this feature is to move the `.svg` rendering away from the legacy gitbooks plugin and into our code writing/build pipeline.__

This has 3 distinct advantages:
1. Makes our rendered sequence diagrams easier to share and view in github
2. Reduces our need of the puml rendering plugin - which frees us up to use other documentation services
3. Makes it easier to spot errors in the plantuml rendering while writing the code, not once it's been rendered on the docs site - not all plantuml renderers are made equal, and if we have `.svg` files in git, then there's much less left up to interpretation at 'presentation time'.

Of course it is not without disadvantages, namely that git commit hooks can be annoying.

The other potential issue is `node-plantuml` looks like it relies on Java behind the scenes, which might not be ideal for some users wishing to contribute to the docs.

### CODE REVIEW

**Comment by lewisdaly** [comment]
@mdebarros what do you think about this approach?

**Comment by mdebarros** [comment]
> @mdebarros what do you think about this approach?

It looks like it will do the job. Is there any reason you are not using `npx` to run the PUML command?

**Comment by mdebarros** [comment]
Also, I noticed the CI/CD job for this PR failed on the `test-svg`. Look at the log and you will see the `find` failed.

**Comment by lewisdaly** [comment]
> Also, I noticed the CI/CD job for this PR failed on the `test-svg`. Look at the log and you will see the `find` failed, but incorrectly reported as passed.

ooh good catch! Thanks @mdebarros

**Comment by lewisdaly** [comment]
> 1.     Is there any reason you are not using npx to run the PUML command?
I thought `npx` had to be installed by the user, so I was thinking this approach was more robust. But it appears that more recently, `npx` is installed along with `npm`, so I'll switch it over to make the script more mangeable.

>2.     Just to understand the flow: ...

Yep, sounds right to me. I might make that a little more obvious in `NOTES.md`

**Comment by lewisdaly** [comment]
@mdebarros wow that took a while, but I switched to using a locally running puml server in docker. 

There were inconsistencies between different versions and installations of plantuml, and this approach seemed the best mix between ensuring that the svg output it deterministic while being easy to install and run both locally and in CI/CD.

**Review by mdebarros — APPROVED** [review]
+1

**Pull request merged**
