### PR TITLE
feat(ci): automate releases

### PR DESCRIPTION
**Pull request by lewisdaly**
Adds basic release automation to the new docs.

When we create a tag or release, the vuepress version tool is run, and a new version is created based on the tag in `website/versioned_docs`. This is about as simple as we can go for this process.

In the future, if we want to tie the version of docs to Mojaloop's helm releases (as I propose), all we need to do is run a daily job that looks for a new release in mojaloop/helm, and creates a new tag in the documentation repo if it finds one.

### CODE REVIEW

**Comment by lewisdaly** [comment]
I tested this with some manual versions, which I'll clean up after this PR is merged

**Review by elnyry-sam-k — APPROVED** [review]

**Comment by lewisdaly** [comment]
@elnyry-sam-k I've fixed the merge conflicts - this is good to go again.

**Comment by lewisdaly** [comment]
hmm build is broken :(

**Comment by kjw000** [comment]
thanks

**Review by elnyry-sam-k — DISMISSED** [review]
Thanks Lewis for reviving this!

approved pending passing of build step

**Comment by lewisdaly** [comment]
Merging per @elnyry-sam-k 's optimistic review ;)

**Pull request merged**
