### PR TITLE
Update KubeInfrastructureArch.svg

### PR DESCRIPTION
**Pull request by DerekCrosson**
Changed 
Alt: DSN Round Robin Fail-over 
to 
Alt: DNS Round Robin Fail-over

### CODE REVIEW

**Comment by DerekCrosson** [comment]
> Hi Derek,
> 
> Thanks for the typo fix on the diagram.
> 
> I am unable to open the diagram in draw.io due to the following error `Not a diagram file`.
> 
> Would be so kind as to ensure that it is an editable SVG `diagram file`.
> 
> Please ping me on slack if you need assistance/clarification.

Hey Miguel!

I've replaced the file on the patch-1 branch, it should open in draw.io now :)

**Comment by DerekCrosson** [comment]
Also updated command to generate token on MacOS and Ubuntu. The command in the current documentation doesn't return the token. Tested on MacOS Mojave and Ubuntu 18.04.

**Comment by mdebarros** [comment]
> Hi Derek,
> 
> Thanks for the typo fix on the diagram.
> 
> I am unable to open the diagram in draw.io due to the following error `Not a diagram file`.
> 
> Would be so kind as to ensure that it is an editable SVG `diagram file`.
> 
> Please ping me on slack if you need assistance/clarification.

Hey @DerekCrosson, 

Apologies for the delay in responding.

the SVG is still an issue as it loads in Draw.io but as a single entity that is not editable.

Am I maybe missing something on my side?

**Comment by DerekCrosson** [comment]
> > Hi Derek,
> > Thanks for the typo fix on the diagram.
> > I am unable to open the diagram in draw.io due to the following error `Not a diagram file`.
> > Would be so kind as to ensure that it is an editable SVG `diagram file`.
> > Please ping me on slack if you need assistance/clarification.
> 
> Hey @DerekCrosson,
> 
> Apologies for the delay in responding.
> 
> the SVG is still an issue as it loads in Draw.io but as a single entity that is not editable.
> 
> Am I maybe missing something on my side?

Hey @mdebarros 

I tried editing the original now (in draw.io) instead of creating my own but I get an alert saying, "Not a diagram file". Not sure how to properly change/edit this file...

**Review by mdebarros — APPROVED** [review]
Thanks!

**Review by mdebarros — CHANGES_REQUESTED** [review]
https://raw.githubusercontent.com/mojaloop/documentation/8e26ae4a0ea25948eab0dceced75b5401bdd1411/deployment-guide/assets/diagrams/deployment/KubeInfrastructureArch.svg <-- Is not editable on Draw.io.

Would you be able to fix it please?

Kind Regards,
Miguel

**Comment by DerekCrosson** [comment]
> https://raw.githubusercontent.com/mojaloop/documentation/8e26ae4a0ea25948eab0dceced75b5401bdd1411/deployment-guide/assets/diagrams/deployment/KubeInfrastructureArch.svg <-- Is not editable on Draw.io.
> 
> Would you be able to fix it please?
> 
> Kind Regards,
> Miguel

Hey, @mdebarros 

The file opens when I open it the way I do in this gif. If I need to edit it so It opens a different way I can do so but I'm not sure how I need to do it, sorry :)

svg-open

**Review by mdebarros — APPROVED** [review]
+1

**Comment by mdebarros** [comment]
> > https://raw.githubusercontent.com/mojaloop/documentation/8e26ae4a0ea25948eab0dceced75b5401bdd1411/deployment-guide/assets/diagrams/deployment/KubeInfrastructureArch.svg <-- Is not editable on Draw.io.
> > Would you be able to fix it please?
> > Kind Regards,
> > Miguel
> 
> Hey, @mdebarros
> 
> The file opens when I open it the way I do in this gif. If I need to edit it so It opens a different way I can do so but I'm not sure how I need to do it, sorry :)
> 
> svg-open

Yup, you are right. If I open the file directly from a local repo copy, then no issues on this side.

Thanks for that!

Kind Regards,
Miguel

**Pull request merged**
