### PR TITLE
feat: migrated scheme rules, json binding rules and pki-best-practice…

### PR DESCRIPTION
**Pull request by meekg33k**
- Created sidebar config for `Scheme Rules` and `JSON Binding` documentation.
- Migrated and cleaned up `Scheme Rules` and `JSON Binding` documentation.
- Updated broken links in existing migrated API documentation

### CODE REVIEW

**Comment by elnyry-sam-k** [comment]
Thanks @meekg33k .

Same comment as on the other PR (use cases PR); please add the section "### 2.1 Open API for FSP Interoperability Specification" (old name) that lists the document set for the Spec (applies to Scheme Rules doc here)..

**Comment by meekg33k** [comment]
Hey @elnyry-sam-k, can we setup a meeting with @lewisdaly to discuss about the changes you've asked that I make?

**Comment by elnyry-sam-k** [comment]
We can, please go ahead; But this change is something you and I discussed already and you agreed to make on the previous PR - https://github.com/mojaloop/documentation/pull/325#issuecomment-907220858 (point number 4 referenced there)

**Comment by elnyry-sam-k** [comment]
Thanks @meekg33k ; the PR shows some conflicts, once those are resolved, we should be good to go..

**Review by elnyry-sam-k — APPROVED** [review]

**Pull request merged**
