### PR TITLE
Fix broken link to README page

### PR DESCRIPTION
**Pull request by mchav**
Link is broken without the file extension.

### CODE REVIEW

**Comment by elnyry-sam-k** [comment]
@mchav - thanks for the PR.. please sign the CLA to move this further

**Comment by mchav** [comment]
@elnyry-sam-k the bot says I've already signed. The circle ci is failing however. Any insight into that?

**Comment by elnyry-sam-k** [comment]
yeah it shows the CLA is signed now.. the CI steps are rerunning now, lets review the result..

**Review by elnyry-sam-k — APPROVED** [review]

**Comment by elnyry-sam-k** [comment]
outdated..

**Comment by mchav** [comment]
The link is still broken.

**Comment by elnyry-sam-k** [comment]
checking @mchav

**Review by elnyry-sam-k — APPROVED** [review]

**Pull request merged**
