### PR TITLE
Bulk Transfers - Adding initial version of the readme file with details regarding the design

### PR DESCRIPTION
**Pull request by elnyry**
1. Readme file containing the steps, DB tables, states and steps correlating with the high-level architecture diagrams

### CODE REVIEW

**Comment by MichaelJBRichards** [comment]
Wrt Point 9 of the design considerations:

"The ordering of the individual transfers need to be considered as well by the Scheme. A Goal for implementation in emerging markets is to maximize the number of transactions involved and so a well designed Scheme may re-order individual transfers in the ascending order of the magnitude of amounts and then process them. But this can be a Scheme consideration"

Did we not solve this question for multiple transfers in a batch inside the switch, where some might be too large to pass the NDC but others could? If so, isn't this the same question?

**Comment by elnyry** [comment]
@MichaelJBRichards thanks for the comment and reviewing this.

I think these are different questions though similar, may be we can have a discussion and you can convince me otherwise. There is no correlation between the size of the bulk and the batch size which is specific to internal implementation of the Switch. Its possible that two items in a given batch belong to two different bulk transfer groups from the same FSP. Moreover, here we are just raising the point for further consideration.

Its another thing that we do not yet use the design for batching (though we have it) in the current implementation.

**Comment by MichaelJBRichards** [comment]
Perhaps I didn't explain myself very well. What I meant was: my recollection of the design decision we took around batching was that we did not need to pre-process or sort a batch to take account of potential problems for individual transfers with the NDC. We would simply reject those transactions which would breach the NDC and continue to process further transactions, forwarding those which would not breach the NDC. It seems to me that any attempt to manage transactions in relation to the NDC will become problematic quite quickly, was all I was saying. There may be some edge cases where individual transfers get rejected because they are in a split batch which might have passed in an integrated batch, but imho a DFSP which doesn't properly manage its NDC to take account of batch payments deserves a degree of pain...

**Comment by elnyry** [comment]
Yes, Michael - Agreed with the understanding on the processing of a batch.

However, for a bulk, following the same (not changing order), would be a default/neutral behavior. Are you saying that we should follow the same here as well?

**Comment by MichaelJBRichards** [comment]
I think I am

**Comment by elnyry** [comment]
Thanks Michael, point noted. I'll go ahead and merge these changes and make updates in later PRs as needed.

**Pull request merged**
