### PR TITLE
feat: migrated and cleaned up signature, encryption and pki docs

### PR DESCRIPTION
**Pull request by meekg33k**
- Created sidebar config for api specification page
- Created sample structure for versioned api specification documentation.
- Migrated and cleaned up `Signature`, `Encryption` and `PKI Best Practices` documentation.

### CODE REVIEW

**Comment by elnyry-sam-k** [comment]
Before merging this - can we please have a quick review @meekg33k

**Comment by meekg33k** [comment]
> Before merging this - can we please have a quick review @meekg33k

Yeah sure @elnyry-sam-k, I opened the PR for review. I can assign you as a reviewer too if you want.

**Review by lewisdaly — APPROVED** [review]

**Comment by lewisdaly** [comment]
Hey Uduak, I forgot (and forgot to mention) that some of this will at some point need review from the CCB Special Interest Groups that overlook these docs.

Maybe we can have a call with @elnyry-sam-k tomorrow or friday to go over the diff for these to get started and make a plan for presenting changes on some of these docs to the CCB.

I'm thinking that that process can also wait until we are merging back into the master branch, so perhaps shouldn't block this PR.

**Comment by elnyry-sam-k** [comment]
Hi Uduak, @meekg33k - thanks for the PR.

Here are some changes I noticed (did a diff here: https://www.diffchecker.com/diff from the files here: https://github.com/mojaloop/mojaloop-specification/tree/master/fspiop-api/documents and the version of the corresponding file on the PR here)

On the PKI best practices doc:
1. The **Table of Contents** section has been removed. (this and #2 below will help with the direct markdown view)
2. Numbering for all sections, sub-sections has been removed 
3. Cross references to sections in the same doc have been removed
4. This section has been removed "### 2.1 Open API for FSP Interoperability Specification" - This one is a blocker - because this is supposed to be present on all the FSPIOP docs

You can quickly view the diff here (for up to 24hrs from when this comment was made): https://www.diffchecker.com/v9Uhm2RB

**Comment by elnyry-sam-k** [comment]
Checked the signature v1.1 doc as well and it looks like the changes in the other docs look the same...

@meekg33k - can you please revisit items #2, #3 and #4 from my comment [above](https://github.com/mojaloop/documentation/pull/325#issuecomment-904656861); others do not affect the content as such, so are fine for now..

**Review by elnyry-sam-k — CHANGES_REQUESTED** [review]
Made comments on the PR to be addressed. Thank you!

**Comment by meekg33k** [comment]
@elnyry-sam-k, I've made some more changes and deleted the `use-cases.md` file. Can you please review/approve so we can go forward with this?

**Review by elnyry-sam-k — APPROVED** [review]

**Comment by elnyry-sam-k** [comment]
ok, thank you Uduak @meekg33k ; approved

**Pull request merged**
