### PR TITLE
feat: manual version 1.0.0

### PR DESCRIPTION
**Pull request by lewisdaly**
- creates a version 1.0.0 for vuepress docs - we will likely rename this later to match helm versions
- added infrastructure for docs.mojaloop.io bucket and associated cloudfront config

### CODE REVIEW

**Review by meekg33k — APPROVED** [review]
Lgtm!

**Comment by meekg33k** [comment]
@lewisdaly, looks like there are some build failures on Circle CI.

**Comment by JasonPolisAdmin** [comment]
sequence diagrams are missing from the published site.
https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html#figure-1

**Comment by lewisdaly** [comment]
Thanks for pointing this out @JasonPolisAdmin - I'll add that to our backlog to fix

**Pull request merged**
