### PR TITLE
Update decimal.md

### PR DESCRIPTION
**Pull request by millerabel**
Correct superscripts in math notation.

### CODE REVIEW

**Comment by millerabel** [comment]
Following merge, how are changed docs “published” to GitBooks? Is this done  is an automated process or does it require manual deploy?

**Comment by elnyry** [comment]
@millerabel , currently the publishing part happens during 'release' process. When a release is created, the publishing happens and the process is yes, automated..

**Comment by millerabel** [comment]
What is the general release schedule for documentation repos? End of sprint, end of PI, or _ad hoc_?

**Comment by kjw000** [comment]
@millerabel - typically we do a release at the end of sprint but also can be done anytime ad hoc.  We also have an item as part of the devops work to have a request for release/update function to immediately deploy gitbook doc changes.

**Comment by millerabel** [comment]
Releasing our documentation together with the sprint release makes sense. I would guess that of cycle _ad hoc_ “hot fixes” will be rare, perhaps for the web site. Good idea to extend the request for immediate release to allow us to handle these when the arise. Thx!

**Pull request merged**
